### ISSUE TITLE
image s3 is the show the same than s2

### ISSUE THREAD

**Issue by SiIencer80** [tenten8401/pterodactyl-rust#2]
pls fix s3 image, i think we need to see there the variable section?

For all looking for the correct pic: 
[image](http://i.imgur.com/YRowna5.png&key=accdee0d752a90c04e7a7d3f103b2ecddc33f6d3c8ef6f9872e3ac824b186124)
[forumlink](https://forums.pterodactyl.io/topic/65-rust-service-for-pterodactyl/)

**Comment by tenten8401** [comment]
We're gonna have an egg for 0.7
