### ISSUE TITLE
Console Blank In New Tabs/Windows

### ISSUE THREAD

**Issue by gamemann** [tenten8401/pterodactyl-rust#3]
Hello, I [reported](https://forums.pterodactyl.io/topic/65-rust-service-for-pterodactyl/?tab=comments#comment-257) this in the Pterodactyl thread for this service.

When I start the server, I can send RCon commands, start/stop/kill server, and look at the usage graphs in that specific tab/window. However, if I try opening the console in another tab/window, the console is blank, stop/start/kill commands do not work, and the usage graphs are empty. 

I made a [video](http://g.gflclan.com/12670d28aa4d2d.mp4) here showing the problem.

Does this issue happen for everybody or just me?

Any help would be highly appreciated!

Thanks.

**Comment by tenten8401** [comment]
Willing to bet you didn't copy the service right, check the logging section in the admin panel service. Restart your daemon after the changes.
